### ISSUE TITLE
Issue in uncurried effect paramaters

### ISSUE THREAD

**Issue by mikesol** [purescript-python/purescript-effect.py#1]
https://github.com/purescript-python/purescript-effect.py/blob/cbb6cc6cc31a9474bef9f16a1a5bb9a041e4a11c/python-ffi/Effect/Uncurried.py#L8

When developing `purescript-aff`, I hit an error coming from the `make_mkEffectFn` function in `Uncurried.py` in `purescript-effect`. I'm not sure if it's my code that's the problem or if the error comes from an issue in purescript-effect. I added two `print` outputs that will hopefully be helpful: one at the callpoint of `module_code` to show the AST:

```python
('line', 32, ('filename', '/home/meeshkan-abel/mike/paff/paff/ffi/Effect/Uncurried.py', ('func', [('var', 'x0')], ('func', [], ('call', ('var', 'fn'), ('var', 'x0')), None, ()), None, ())))
```

and one to show all the arguments being passed to `types.CodeType`:

```python
1 0 1 2 65 b'd\x01d\x02\x84\x00S\x00' ('', <code object lambda:32 at 0x7fdc90471930, file "/home/meeshkan-abel/mike/paff/paff/ffi/Effect/Uncurried.py", line 32>, 'lambda:32') () (('var', 'x0'),) /home/meeshkan-abel/mike/paff/paff/ffi/Effect/Uncurried.py lambda:32 32 b'' () ()
```

resulting in the following error:

```bash
  File "/home/meeshkan-abel/mike/paff/.venv/lib/python3.7/site-packages/bytecode/concrete.py", line 382, in to_code
    tuple(self.cellvars),
TypeError: name tuples must contain only strings, not 'tuple'
```

It's here that you can see the culprit: the argument `(('var','x0'),)` should not be passed to `types.CodeType`, as it is expecting a tuple of strings and not a tuple of a tuple of strings.

Unfortunately, because I do not understand the inner workings of `make_mkEffectFn`, I'm not sure what an appropriate fix would be. Hopefully the original author(s) will spot where the error is and can make the fix. Thanks!

**Comment by thautwarm** [comment]
Hello Mike.
I know you might know this but in case, I'd clarify:
the python file is basically a Python rewrite of [purescript-effect: Effect/Uncurried.js](https://github.com/purescript/purescript-effect/blob/master/src/Effect/Uncurried.js).


The problem seems to be at here: https://github.com/purescript-python/purescript-effect.py/blob/cbb6cc6cc31a9474bef9f16a1a5bb9a041e4a11c/python-ffi/Effect/Uncurried.py#L39

By searching the documentation [PySExpr#define](https://htmlpreview.github.io/?https://raw.githubusercontent.com/thautwarm/PySExpr/gh-pages/docs/py_sexpr/terms.html#py_sexpr.terms.define), you'd see the second arguments should be a list of string, but I give a `List[PySExpr]`.

The reason why I use PySExpr to write this module is due to my limitation of efforts, but if you think it harmful we can negotiate, and may simply rewrite everything in vanilla python instead of using PySExpr.

Hence, instead of 
```python
lam = define(None, [var(arg)], lam) 
```
it should be

```python
lam = define(None, [arg], lam) 
```

(`PySExpr` is an opaque type which is actually represented with nested tuples)

**Comment by thautwarm** [comment]
If you could confirm this fix is working, you might try to understand it and make a PR?

**Comment by mikesol** [comment]
Hi!

It works, thanks for this!

There's also one more bug - the last three lines of the file should be:

```python
for i in range(1, 11):
    make_mkEffectFn(i)
    make_runEffectFn(i)
```

I'll make a PR for both & thanks.

**Comment by mikesol** [comment]
Fixed in current master
